name: Scale test

on:
  push:
    branches:
      - master

jobs:
  scale-test:
    runs-on: runner
    strategy:
      matrix:
        job: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: sudo apt update -y
      - name: Run a one-line script
        run: echo scale test ${{ matrix.job }} finished!